### ISSUE TITLE
S1E firmwares 2.0.8_0002支持了吗

### ISSUE THREAD

**Issue by summmer121** [niceboygithub/AqaraSmartSwitchS1E#12]
现在支持2.0.8固件了吗，我看已经add S1E firmwares 2.0.8_0002，但是redeme里还写着不要升级

**Comment by niceboygithub** [comment]
Don't use official firmware to avoid disabled telnet. Use modified firmware 2.0.8.

**Comment by summmer121** [comment]
> Don't use official firmware to avoid disabled telnet. Use modified firmware 2.0.8.

But I am currently in version 2.0.8. Can this still be upgraded to the modified version 2.0.8 in your code

**Comment by niceboygithub** [comment]
Yes

**Comment by summmer121** [comment]
thanks
