### ISSUE TITLE
Cant interrupt the boot sequence

### ISSUE THREAD

**Issue by Zack-Xu** [niceboygithub/AqaraSmartSwitchS1E#17]
I got a S1E which version is 2.0.9 . Of course， it dont support telnet. So I try to interrupt the boot sequence by holding my "Enter"。But it seems not work. I have tryed a lot of times.
There is something different between your hardware and my S1E，I got a fudanmicro NAND Flash not 'foresee'.
**Is it possible I soldered off this nand and programmed the flash directly.** In that way ， I need a complete firmware or something like that。contains APP and uboot .
![微信图片_20231219141117](https://github.com/niceboygithub/AqaraSmartSwitchS1E/assets/41894445/39900f05-4b52-4b3a-9b1d-a9895c7f5e51)

**Comment by g1335333249** [comment]
Me too, any solutions?

**Comment by g1335333249** [comment]
Me too, any solutions?

**Comment by Zack-Xu** [comment]
Actually, this problem has been solved.
 You need to directly short-circuit the `cspin` and `vccpin` of the flash during the boot phase to interrupt the boot and then enter the Uboot. 
By the way, you need to refer to the datasheet of the corresponding NANDflash and use a multimeter to confirm the relationship between the NANDflash pins and nearby test pads
**This method is relatively dangerous for chips.** And the boot process is very fast, basically at the moment of power on, you need to synchronously short circuit the `CSPin` and `VCCPin`.
 I operated it by short circuiting with metal tweezers. I tried about 10 times and eventually entered UBoot. Sometimes it may enter Uboot but the flash no longer recognizes it, so try again at this time. The following operations are consistent with the tutorial.

**Comment by g1335333249** [comment]
> Actually, this problem has been solved.
> You need to directly short-circuit the `cspin` and `vccpin` of the flash during the boot phase to interrupt the boot and then enter the Uboot.
> By the way, you need to refer to the datasheet of the corresponding NANDflash and use a multimeter to confirm the relationship between the NANDflash pins and nearby test pads
> **This method is relatively dangerous for chips.** And the boot process is very fast, basically at the moment of power on, you need to synchronously short circuit the `CSPin` and `VCCPin`.
> I operated it by short circuiting with metal tweezers. I tried about 10 times and eventually entered UBoot. Sometimes it may enter Uboot but the flash no longer recognizes it, so try again at this time. The following operations are consistent with the tutorial.

You should be Chinese, can I add you on WeChat for advice?

**Comment by Zack-Xu** [comment]
17858962835



发自我的iPhone


------------------ Original ------------------
From: g1335333249 ***@***.***&gt;
Date: Fri,Dec 29,2023 0:52 PM
To: niceboygithub/AqaraSmartSwitchS1E ***@***.***&gt;
Cc: Zack-Xu ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [niceboygithub/AqaraSmartSwitchS1E] Cant interrupt the bootsequence (Issue #17)





  
Actually, this problem has been solved.
 You need to directly short-circuit the cspin and vccpin of the flash during the boot phase to interrupt the boot and then enter the Uboot.
 By the way, you need to refer to the datasheet of the corresponding NANDflash and use a multimeter to confirm the relationship between the NANDflash pins and nearby test pads
 This method is relatively dangerous for chips. And the boot process is very fast, basically at the moment of power on, you need to synchronously short circuit the CSPin and VCCPin.
 I operated it by short circuiting with metal tweezers. I tried about 10 times and eventually entered UBoot. Sometimes it may enter Uboot but the flash no longer recognizes it, so try again at this time. The following operations are consistent with the tutorial.
  
You should be Chinese, can I add you on WeChat for advice?
