### ISSUE TITLE
Changing Language

### ISSUE THREAD

**Issue by earlywaff** [niceboygithub/AqaraSmartSwitchS1E#2]
Hi! Is it possible to change the language? From Chinese to English?

**Comment by niceboygithub** [comment]
It is doable but current I will not do it. Cause two reasons.
1. Need spend too much to implement.
2. Aqara may add multi-language support in the future.

**Comment by ashottonoyan** [comment]
Is it a matter of translating text files, or will it require compilation?

**Comment by Kepete** [comment]
Also looking for English, that's the reason why still haven't bought one. 
Seems Aqara is releasing new models of the display, but not updating the S1E with English. But then again for example Scene Panel S1 which supports English does not have Homekit support.

**Comment by niceboygithub** [comment]
firmware 2.0.8 now support three languages, "English", "Simplified Chinese", "Traditional Chinese" now.
If you use "asetprop persist.sys.oversea true" command via telnet, you can see the language menu of UI settings.

**Comment by ashottonoyan** [comment]
Changing the language to English doesn't work in 2.0.9_0006

**Comment by xTipo** [comment]
hello niceboy, i have now two units of switch and try to log in via tellnet, but it ask for login and pwd.
Do you know original login creditians?

**Comment by niceboygithub** [comment]
Each S1E has different password. Please follow the guidelines to clear the login password.
