### ISSUE TITLE
How to access cli wirelessly after enabling telnetd

### ISSUE THREAD

**Issue by yzlnew** [niceboygithub/AqaraSmartSwitchS1E#24]
Custom firmware is flashed according to https://github.com/niceboygithub/AqaraSmartSwitchS1E/blob/master/homeassistant/telnet.md .
I want to update to a new custom firmware. How can I access the cli without doing that again?

**Comment by niceboygithub** [comment]
telnet to S11E, the enter the commands 
'''

cd /tmp && wget -O /tmp/curl "http://master.dl.sourceforge.net/project/aqarahub/binutils/curl?viasf=1" && chmod a+x /tmp/curl
/tmp/curl -s -k -L -o /tmp/s1e_update.sh https://raw.githubusercontent.com/niceboygithub/AqaraSmartSwitchS1E/master/firmwares/modified/S1E/s1e_update.sh
chmod a+x /tmp/s1e_update.sh && /tmp/s1e_update.sh
'''

**Comment by yzlnew** [comment]
Thanks! I forgot I could telnet its IP directly.
