### ISSUE TITLE
Error message in check_mqtt method

### ISSUE THREAD

**Issue by dmr1987** [niceboygithub/AqaraSmartSwitchS1E#3]
Line 53 in file ubus_monitor.sh
`error "The mosquitto_sub or mosquitto_sub are not exist!"`
please change to:
`error "The mosquitto_sub or mosquitto_`**pub** `are not exist!"`
Same changes on line 87 at file res_monitor.sh
Line 61 at mqtt_sub.sh
Line 65 at install_1e2ha.sh

**Comment by niceboygithub** [comment]
Thanks.
Will be correct it next release.
