### ISSUE TITLE
Switch status not read

### ISSUE THREAD

**Issue by ashottonoyan** [niceboygithub/AqaraSmartSwitchS1E#6]
HA doesn't know if switch is on or off.

<img width="380" alt="Screenshot 2023-03-05 at 4 54 38 PM" src="https://user-images.githubusercontent.com/612529/222961616-93d04c7f-e014-4167-a00c-6369f3c5f7f1.png">

MQTT has the data:
<img width="994" alt="Screenshot 2023-03-05 at 4 55 26 PM" src="https://user-images.githubusercontent.com/612529/222961693-6207f3a3-8e9f-43e4-ad17-b342d1a045a5.png">

**Comment by happyhaha1** [comment]
Has this problem been solved？

**Comment by niceboygithub** [comment]
I did not get such problem in my side.
