### ISSUE TITLE
Any way to flash modified firmware via UART?

### ISSUE THREAD

**Issue by andywei1996** [niceboygithub/AqaraSmartSwitchS1E#7]
Hi, thanks for this good repo!
Unfortunately, I’ve updated my S1E to 2.6.0 version before I found this repo and I can’t get a telnet access to the panel now.
I’ve followed the instruction in telnet.md document and removed the password successfully, next step is flash modified firmware into S1E, but my S1E can’t establish WiFi connection in this state so I can’t run command to download shell scripts and performing a firmware modify.
So now I would like to know is there any way to flash the modified firmware to S1E? Is it possible to do this with UART?
Thanks!

**Comment by niceboygithub** [comment]
Did you restart S1E after remove the password?

After S1E restart, it shall automatically connect to WiFi AP.

**Comment by andywei1996** [comment]
@niceboygithub Yes I reboot S1E after remove the password.
I reboot S1E by remove the 5V power and reconnect it.

**Comment by niceboygithub** [comment]
Did you finish provision it with Aqara Home app?

**Comment by andywei1996** [comment]
@niceboygithub Yes, I’ve do it.

**Comment by andywei1996** [comment]
@niceboygithub When I put it back to wall dock it bootup well and establish WiFi connection, but I can’t telnet to S1E, console shows Connection refused.

**Comment by niceboygithub** [comment]
The latest firmware was disabling  telnetd so you need to flash before put it back on the wall.

**Comment by andywei1996** [comment]
@niceboygithub Thanks for your support!
Finally, I flash the modified firmware successfully, following is my step:

1. Follow telnet.md document to remove password of root user.
2. Reboot S1E, and the device stopped after the kernel loaded. The console prompted two error messages, and a WiFi connection can't be established in this state.
3. Put S1E back on the wall without remove UART line, and then S1E bootup successfully, WiFi connected.
4. Follow telnet.md to flash modified firmware and install s1e2ha via UART console and it's successfully, now telnet and mosquitto work as well.

Could it be that when S1E can not communicate with wall dock, system will not boot up because S1E judgement this is not a normal state?

**Comment by niceboygithub** [comment]
S1E may more power while using WiFi. If you provide enough power, it won't connect to WiFi. When you put it on the wall, the power is enough absolutely.
